### ISSUE TITLE
[Setup Script] Wrong extension when downloading ITSM NG

### ISSUE THREAD

**Issue by nothing-fr** [itsmng/itsmng-docker#1]
Hi,

The extension in github release section is `.tgz` not `.tar.gz` : 

https://github.com/itsmng/itsmng-docker/blob/982e6d40dd3f8b7cc0b053095f742f8a6e40177c/setup.sh#L87
https://github.com/itsmng/itsmng-docker/blob/982e6d40dd3f8b7cc0b053095f742f8a6e40177c/setup.sh#L88-L89

The script cannot download/extract correctly the archive.

Best regards.

**Comment by itsmdevteam** [comment]
Hi,

The new docker implementation should fix this issue.
We are going to release the image on the docker hub during the next weeks.
