### ISSUE TITLE
[BUG] PHP Deprecated function

### ISSUE THREAD

**Issue by charleneauger** [itsmng/itsmng-docker#15]
Hi,

When you switch to `debug` mode on the docker version, the display is polluted with `PHP Deprecated function` messages.

We can note two different messages:
```
PHP Deprecated function (8192): Creation of dynamic property DBmysqlIterator::$parameters is deprecated in /var/www/itsm-ng/inc/dbmysqliterator.class.php at line 112
PHP Deprecated function (8192): Creation of dynamic property User::$right is deprecated in /var/www/itsm-ng/inc/commondbtm.class.php at line 2983
```

ITSM-NG docker version : 1.6.0

Best regards,
Charlène

**Comment by AntoineLemarchand** [comment]
Hi,

Thank you for your feedback. These notices are from php8.x and will be fixed in the next version. We are not planning to backport these patches to 1.6.x as of right now, but we might consider it later on.

Best regards,
Antoine.

**Comment by AntoineLemarchand** [comment]
Hi,

Thank you for your feedback. The latest version of the container has been shipped with a newer version of PHP. We are currently working on a minor version to address these deprecated notices.

Best regards,
Antoine

**Comment by minzords** [comment]
Hi,

Your problem has been corrected in ITSM-NG version 1.6.2, you can therefore use this version in docker.

Best regards,
Florian

**Comment by charleneauger** [comment]
Hi @AntoineLemarchand, @minzords,

Thanks.

I could see that you had pushed the new 1.6.2 image.

Is it possible to do the same for docker files ?
Will this GitHub repository be updated or is it intended to be archived ?

Best regards,
Charlene

**Comment by minzords** [comment]
Hello,

The image is upload on the Docker Hub (https://hub.docker.com/layers/itsmng/itsm-ng/1.6.2/images/sha256-f38b9ba4c1894e2abea1c8cc1f9b1f627a22bf3bc8e6d56d683d3fc08809ad9b?context=repo)

Have you updated your docker-compose.yml ?

Best regards,
Florian Blanchet
